--------------------------------------------------------
-- Archivo creado  - domingo-septiembre-23-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEC_ADMINISTRADORES
--------------------------------------------------------

   CREATE SEQUENCE  "IISSI"."SEC_ADMINISTRADORES"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_ARTICULOS
--------------------------------------------------------

   CREATE SEQUENCE  "IISSI"."SEC_ARTICULOS"  MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_CATEGORIAS
--------------------------------------------------------

   CREATE SEQUENCE  "IISSI"."SEC_CATEGORIAS"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 83 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_CLIENTES
--------------------------------------------------------

   CREATE SEQUENCE  "IISSI"."SEC_CLIENTES"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 91 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_LINEAPEDIDOS
--------------------------------------------------------

   CREATE SEQUENCE  "IISSI"."SEC_LINEAPEDIDOS"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_PEDIDOS
--------------------------------------------------------

   CREATE SEQUENCE  "IISSI"."SEC_PEDIDOS"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADMINISTRADORES
--------------------------------------------------------

  CREATE TABLE "IISSI"."ADMINISTRADORES" 
   (	"IDADMINISTRADOR" NUMBER(25,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"DNI" VARCHAR2(10 BYTE), 
	"TELEFONO" NUMBER(9,0), 
	"DOMICILIO" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(250 BYTE), 
	"PASS" VARCHAR2(250 BYTE), 
	"FECHANACIMIENTO" DATE, 
	"FOTO" VARCHAR2(250 BYTE), 
	"PERFIL" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ARTICULOS
--------------------------------------------------------

  CREATE TABLE "IISSI"."ARTICULOS" 
   (	"IDARTICULO" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"FECHAALTA" DATE, 
	"CANTIDAD" NUMBER(*,0), 
	"PESO" NUMBER(*,0), 
	"DIMENSIONN" VARCHAR2(50 BYTE), 
	"MATERIAL" VARCHAR2(50 BYTE), 
	"PRECIOCOMPRA" NUMBER(*,0), 
	"PRECIOVENTA" NUMBER(*,0), 
	"FKIDCATEGORIA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORIAS
--------------------------------------------------------

  CREATE TABLE "IISSI"."CATEGORIAS" 
   (	"IDCATEGORIA" NUMBER(38,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "IISSI"."CLIENTES" 
   (	"IDCLIENTE" NUMBER(10,0), 
	"DNI" VARCHAR2(10 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDOS" VARCHAR2(50 BYTE), 
	"DOMICILIO" VARCHAR2(50 BYTE), 
	"TELEFONO" VARCHAR2(9 BYTE), 
	"CORREOELECTRONICO" VARCHAR2(50 BYTE), 
	"PASS" VARCHAR2(50 BYTE), 
	"FECHANACIMIENTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LINEAPEDIDOS
--------------------------------------------------------

  CREATE TABLE "IISSI"."LINEAPEDIDOS" 
   (	"IDLINEAPEDIDO" NUMBER(10,0), 
	"CANTIDAD" NUMBER(*,0), 
	"PRECIO" NUMBER(5,2), 
	"FKIDPEDIDO" NUMBER(10,0), 
	"FKIDARTICULO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PEDIDOS
--------------------------------------------------------

  CREATE TABLE "IISSI"."PEDIDOS" 
   (	"IDPEDIDO" NUMBER(10,0), 
	"FECHAPEDIDO" DATE, 
	"PRECIOTOTAL" NUMBER(5,2), 
	"ESTADOPAGO" VARCHAR2(250 BYTE), 
	"FKIDCLIENTE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into IISSI.ADMINISTRADORES
SET DEFINE OFF;
Insert into IISSI.ADMINISTRADORES (IDADMINISTRADOR,NOMBRE,APELLIDO,DNI,TELEFONO,DOMICILIO,EMAIL,PASS,FECHANACIMIENTO,FOTO,PERFIL) values ('42','Nombre','Apellidos','28849269R','123456789','Domicilio','correo@correo.correo','pass',to_date('03/01/10','DD/MM/RR'),null,'Admin');
Insert into IISSI.ADMINISTRADORES (IDADMINISTRADOR,NOMBRE,APELLIDO,DNI,TELEFONO,DOMICILIO,EMAIL,PASS,FECHANACIMIENTO,FOTO,PERFIL) values ('66','Nombre','Apellidos','12345678Z','123456789','Domicilio','correo@correo.correo','pass',to_date('01/01/10','DD/MM/RR'),null,'Empleado');
Insert into IISSI.ADMINISTRADORES (IDADMINISTRADOR,NOMBRE,APELLIDO,DNI,TELEFONO,DOMICILIO,EMAIL,PASS,FECHANACIMIENTO,FOTO,PERFIL) values ('62','Nombre','Apellidos','00000000T','123456789','Domicilio','correo@correo.correo','pass',to_date('01/01/17','DD/MM/RR'),null,'Admin');
Insert into IISSI.ADMINISTRADORES (IDADMINISTRADOR,NOMBRE,APELLIDO,DNI,TELEFONO,DOMICILIO,EMAIL,PASS,FECHANACIMIENTO,FOTO,PERFIL) values ('64','Nombre','Apellidos','12345678Z','123456789','Domicilio','correo@correo.correo','pass',to_date('01/01/16','DD/MM/RR'),null,'Empleado');
Insert into IISSI.ADMINISTRADORES (IDADMINISTRADOR,NOMBRE,APELLIDO,DNI,TELEFONO,DOMICILIO,EMAIL,PASS,FECHANACIMIENTO,FOTO,PERFIL) values ('68','Nombre','Apellido','12345678Z','123456789','Domicilio','correo@correo.correo','nuevaPass',to_date('01/01/10','DD/MM/RR'),null,'Empleado');
Insert into IISSI.ADMINISTRADORES (IDADMINISTRADOR,NOMBRE,APELLIDO,DNI,TELEFONO,DOMICILIO,EMAIL,PASS,FECHANACIMIENTO,FOTO,PERFIL) values ('70','Nombre','Apellidos','12345678Z','123456789','Domicilio','correo@correo.correo','nueva pass',to_date('01/01/10','DD/MM/RR'),null,'Empleado');
Insert into IISSI.ADMINISTRADORES (IDADMINISTRADOR,NOMBRE,APELLIDO,DNI,TELEFONO,DOMICILIO,EMAIL,PASS,FECHANACIMIENTO,FOTO,PERFIL) values ('72','Nombre','Apellidos','00000000T','0','Domicilio','correo@correo.correo','nuevapass',to_date('01/01/96','DD/MM/RR'),null,'Empleado');
REM INSERTING into IISSI.ARTICULOS
SET DEFINE OFF;
Insert into IISSI.ARTICULOS (IDARTICULO,NOMBRE,FECHAALTA,CANTIDAD,PESO,DIMENSIONN,MATERIAL,PRECIOCOMPRA,PRECIOVENTA,FKIDCATEGORIA) values ('82','aab',to_date('03/06/18','DD/MM/RR'),'3','5','1x1x1','aaaa','3','3','64');
Insert into IISSI.ARTICULOS (IDARTICULO,NOMBRE,FECHAALTA,CANTIDAD,PESO,DIMENSIONN,MATERIAL,PRECIOCOMPRA,PRECIOVENTA,FKIDCATEGORIA) values ('102','aaa',to_date('06/06/18','DD/MM/RR'),'3','5','1x1x1','aaaa','4','4','44');
Insert into IISSI.ARTICULOS (IDARTICULO,NOMBRE,FECHAALTA,CANTIDAD,PESO,DIMENSIONN,MATERIAL,PRECIOCOMPRA,PRECIOVENTA,FKIDCATEGORIA) values ('122','mueble',to_date('23/09/18','DD/MM/RR'),'10','50','1x2x3','Uranio','200','300','44');
Insert into IISSI.ARTICULOS (IDARTICULO,NOMBRE,FECHAALTA,CANTIDAD,PESO,DIMENSIONN,MATERIAL,PRECIOCOMPRA,PRECIOVENTA,FKIDCATEGORIA) values ('124','NuevoMueble',to_date('23/09/18','DD/MM/RR'),'300','2','1x1x1','Oxígeno','10','15','64');
REM INSERTING into IISSI.CATEGORIAS
SET DEFINE OFF;
Insert into IISSI.CATEGORIAS (IDCATEGORIA,NOMBRE,DESCRIPCION) values ('42','Nombre','Descripcion nueva');
Insert into IISSI.CATEGORIAS (IDCATEGORIA,NOMBRE,DESCRIPCION) values ('44','Nombre','Descripción número');
Insert into IISSI.CATEGORIAS (IDCATEGORIA,NOMBRE,DESCRIPCION) values ('64','NuevaCategoria','Esto es una descripción');
REM INSERTING into IISSI.CLIENTES
SET DEFINE OFF;
REM INSERTING into IISSI.LINEAPEDIDOS
SET DEFINE OFF;
REM INSERTING into IISSI.PEDIDOS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Trigger CREAR_IDADMINISTRADOR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IISSI"."CREAR_IDADMINISTRADOR" 

    BEFORE INSERT ON ADMINISTRADORES FOR EACH ROW 
BEGIN 

    SELECT SEC_ADMINISTRADORES.NextVal into :NEW.IdAdministrador FROM DUAL; 
end;

/
ALTER TRIGGER "IISSI"."CREAR_IDADMINISTRADOR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREAR_IDARTICULO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IISSI"."CREAR_IDARTICULO" 
    BEFORE INSERT ON Articulos FOR EACH ROW 
BEGIN 
    SELECT SEC_ARTICULOS.NEXTVAL into :NEW.IdArticulo FROM DUAL; 
end;

/
ALTER TRIGGER "IISSI"."CREAR_IDARTICULO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREAR_IDCATEGORIA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IISSI"."CREAR_IDCATEGORIA" 
    BEFORE INSERT ON Categorias FOR EACH ROW 
BEGIN 
    SELECT SEC_CATEGORIAS.NextVAL into :NEW.IdCategoria FROM DUAL; 
end;

/
ALTER TRIGGER "IISSI"."CREAR_IDCATEGORIA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREAR_IDCLIENTE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IISSI"."CREAR_IDCLIENTE" 
    BEFORE INSERT ON CLIENTES FOR EACH ROW 
BEGIN 
    SELECT SEC_CLIENTES.NEXTVAL into :NEW.IdCliente FROM DUAL; 
end;

/
ALTER TRIGGER "IISSI"."CREAR_IDCLIENTE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREAR_IDLINEAPEDIDO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IISSI"."CREAR_IDLINEAPEDIDO" 
    BEFORE INSERT ON LINEAPEDIDOS FOR EACH ROW 
BEGIN 
    SELECT SEC_LINEAPEDIDOS.NEXTVAL into :NEW.IdLineaPedido FROM DUAL; 
end;

/
ALTER TRIGGER "IISSI"."CREAR_IDLINEAPEDIDO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREAR_IDPEDIDO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IISSI"."CREAR_IDPEDIDO" 
    BEFORE INSERT ON PEDIDOS FOR EACH ROW 
BEGIN 
    SELECT SEC_PEDIDOS.NEXTVAL into :NEW.IdPedido FROM DUAL; 
end;

/
ALTER TRIGGER "IISSI"."CREAR_IDPEDIDO" ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIAS
--------------------------------------------------------

  ALTER TABLE "IISSI"."CATEGORIAS" ADD PRIMARY KEY ("IDCATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IISSI"."CATEGORIAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."CATEGORIAS" MODIFY ("IDCATEGORIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "IISSI"."CLIENTES" ADD PRIMARY KEY ("IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IISSI"."CLIENTES" MODIFY ("FECHANACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."CLIENTES" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."CLIENTES" MODIFY ("CORREOELECTRONICO" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."CLIENTES" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."CLIENTES" MODIFY ("DOMICILIO" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."CLIENTES" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."CLIENTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."CLIENTES" MODIFY ("DNI" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."CLIENTES" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMINISTRADORES
--------------------------------------------------------

  ALTER TABLE "IISSI"."ADMINISTRADORES" ADD CONSTRAINT "CHECK_ADMINISTRADORES_PERFIL" CHECK (Perfil IN ('Empleado', 'Admin')) ENABLE;
  ALTER TABLE "IISSI"."ADMINISTRADORES" ADD PRIMARY KEY ("IDADMINISTRADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IISSI"."ADMINISTRADORES" MODIFY ("PERFIL" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ADMINISTRADORES" MODIFY ("FECHANACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ADMINISTRADORES" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ADMINISTRADORES" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ADMINISTRADORES" MODIFY ("DOMICILIO" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ADMINISTRADORES" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ADMINISTRADORES" MODIFY ("DNI" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ADMINISTRADORES" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ADMINISTRADORES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ADMINISTRADORES" MODIFY ("IDADMINISTRADOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ARTICULOS
--------------------------------------------------------

  ALTER TABLE "IISSI"."ARTICULOS" ADD PRIMARY KEY ("IDARTICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IISSI"."ARTICULOS" ADD CONSTRAINT "CKPRECIOCOMPRA" CHECK (PrecioCompra > 0) ENABLE;
  ALTER TABLE "IISSI"."ARTICULOS" ADD CONSTRAINT "PESO" CHECK (Peso > 0) ENABLE;
  ALTER TABLE "IISSI"."ARTICULOS" ADD CONSTRAINT "CKCANTIDADA" CHECK (Cantidad > 0) ENABLE;
  ALTER TABLE "IISSI"."ARTICULOS" MODIFY ("FKIDCATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ARTICULOS" MODIFY ("PRECIOVENTA" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ARTICULOS" MODIFY ("PRECIOCOMPRA" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ARTICULOS" MODIFY ("MATERIAL" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ARTICULOS" MODIFY ("DIMENSIONN" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ARTICULOS" MODIFY ("PESO" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ARTICULOS" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ARTICULOS" MODIFY ("FECHAALTA" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ARTICULOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."ARTICULOS" MODIFY ("IDARTICULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PEDIDOS
--------------------------------------------------------

  ALTER TABLE "IISSI"."PEDIDOS" ADD CONSTRAINT "CHECK_PEDIDOS_ESTADOPAGO" CHECK (EstadoPago IN ('Pagada', 'Pendiente')) ENABLE;
  ALTER TABLE "IISSI"."PEDIDOS" ADD PRIMARY KEY ("IDPEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IISSI"."PEDIDOS" ADD CONSTRAINT "PRECIOTOTAL" CHECK (PrecioTotal > 0) ENABLE;
  ALTER TABLE "IISSI"."PEDIDOS" MODIFY ("FKIDCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."PEDIDOS" MODIFY ("ESTADOPAGO" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."PEDIDOS" MODIFY ("PRECIOTOTAL" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."PEDIDOS" MODIFY ("FECHAPEDIDO" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."PEDIDOS" MODIFY ("IDPEDIDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LINEAPEDIDOS
--------------------------------------------------------

  ALTER TABLE "IISSI"."LINEAPEDIDOS" ADD PRIMARY KEY ("IDLINEAPEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IISSI"."LINEAPEDIDOS" ADD CONSTRAINT "PRECIO" CHECK (Precio > 0) ENABLE;
  ALTER TABLE "IISSI"."LINEAPEDIDOS" MODIFY ("FKIDARTICULO" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."LINEAPEDIDOS" MODIFY ("FKIDPEDIDO" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."LINEAPEDIDOS" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."LINEAPEDIDOS" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "IISSI"."LINEAPEDIDOS" MODIFY ("IDLINEAPEDIDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ARTICULOS
--------------------------------------------------------

  ALTER TABLE "IISSI"."ARTICULOS" ADD FOREIGN KEY ("FKIDCATEGORIA")
	  REFERENCES "IISSI"."CATEGORIAS" ("IDCATEGORIA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LINEAPEDIDOS
--------------------------------------------------------

  ALTER TABLE "IISSI"."LINEAPEDIDOS" ADD FOREIGN KEY ("FKIDPEDIDO")
	  REFERENCES "IISSI"."PEDIDOS" ("IDPEDIDO") ENABLE;
  ALTER TABLE "IISSI"."LINEAPEDIDOS" ADD FOREIGN KEY ("FKIDARTICULO")
	  REFERENCES "IISSI"."ARTICULOS" ("IDARTICULO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDOS
--------------------------------------------------------

  ALTER TABLE "IISSI"."PEDIDOS" ADD FOREIGN KEY ("FKIDCLIENTE")
	  REFERENCES "IISSI"."CLIENTES" ("IDCLIENTE") ENABLE;
